export interface Server {
  id: string;
  name: string;
  host: string;
  port: number;
  description: string;
  version: string;
  online: boolean;
  players: number;
  maxPlayers: number;
  favorite: boolean;
  ping?: number;
  tag?: string;
}

export type Tab = "all" | "favorites";

export const INITIAL_SERVERS: Server[] = [
  {
    id: "1",
    name: "CubeCraft Games",
    host: "mco.cubecraft.net",
    port: 19132,
    description: "Мини-игры, BedWars, SkyWars",
    version: "1.21",
    online: true,
    players: 8412,
    maxPlayers: 15000,
    favorite: true,
    ping: 42,
    tag: "Мини-игры",
  },
  {
    id: "2",
    name: "Hive Games",
    host: "geo.hivebedrock.network",
    port: 19132,
    description: "SkyWars, Murder Mystery, DeathRun",
    version: "1.21",
    online: true,
    players: 5230,
    maxPlayers: 10000,
    favorite: true,
    ping: 58,
    tag: "PvP",
  },
  {
    id: "3",
    name: "Mineplex",
    host: "pe.mineplex.com",
    port: 19132,
    description: "Классический сервер с огромным выбором режимов",
    version: "1.20",
    online: true,
    players: 1800,
    maxPlayers: 5000,
    favorite: false,
    ping: 120,
    tag: "Классика",
  },
  {
    id: "4",
    name: "Lifeboat Network",
    host: "mco.lbsg.net",
    port: 19132,
    description: "Survival, SkyBlock, Hunger Games",
    version: "1.21",
    online: false,
    players: 0,
    maxPlayers: 8000,
    favorite: false,
    ping: undefined,
    tag: "Выживание",
  },
  {
    id: "5",
    name: "Nether Games",
    host: "play.nethergames.org",
    port: 19132,
    description: "Фракции, Дуэли, Ивенты",
    version: "1.21",
    online: true,
    players: 3100,
    maxPlayers: 6000,
    favorite: false,
    ping: 85,
    tag: "PvP",
  },
  {
    id: "6",
    name: "WildCraft SMP",
    host: "wild.mcpehub.net",
    port: 19132,
    description: "Ванильное выживание с нуля — никаких доноров, честная игра. Сезон обновляется каждые 3 месяца",
    version: "1.21",
    online: true,
    players: 247,
    maxPlayers: 500,
    favorite: false,
    ping: 34,
    tag: "Выживание",
  },
  {
    id: "7",
    name: "IronAge SMP",
    host: "ironage.mcpehub.net",
    port: 19132,
    description: "Хардкорное выживание — смерть сбрасывает прогресс. Экономика на основе железа и ресурсов",
    version: "1.20",
    online: true,
    players: 89,
    maxPlayers: 200,
    favorite: false,
    ping: 51,
    tag: "Хардкор",
  },
  {
    id: "8",
    name: "CraftLand Origins",
    host: "origins.mcpehub.net",
    port: 19132,
    description: "Выживание с расами: маг, охотник, строитель — каждый со своими способностями",
    version: "1.21",
    online: true,
    players: 412,
    maxPlayers: 800,
    favorite: false,
    ping: 67,
    tag: "RPG",
  },
  {
    id: "9",
    name: "StoneAge PE",
    host: "stone.mcpehub.net",
    port: 19132,
    description: "Поддержка версий 1.16–1.21. Выживание с кланами, захват территорий и еженедельные ивенты",
    version: "1.16+",
    online: true,
    players: 634,
    maxPlayers: 1200,
    favorite: false,
    ping: 44,
    tag: "Выживание",
  },
  {
    id: "10",
    name: "DeepWorld SMP",
    host: "deep.mcpehub.net",
    port: 19132,
    description: "Выживание под землёй — старт в пещере без инструментов. Особый рельеф, только подземные биомы",
    version: "1.21",
    online: true,
    players: 178,
    maxPlayers: 400,
    favorite: false,
    ping: 29,
    tag: "Выживание",
  },
  {
    id: "11",
    name: "NovaCraft SMP",
    host: "nova.mcpehub.net",
    port: 19132,
    description: "Выживание для новичков: обучение, подсказки, защита спавна. Поддержка с 1.18",
    version: "1.18+",
    online: true,
    players: 521,
    maxPlayers: 1000,
    favorite: false,
    ping: 72,
    tag: "Новички",
  },
  {
    id: "12",
    name: "FrostByte SMP",
    host: "frost.mcpehub.net",
    port: 19132,
    description: "Зимний мир — только снежные биомы, повышенная сложность, особые крафты для выживания в холоде",
    version: "1.21",
    online: false,
    players: 0,
    maxPlayers: 300,
    favorite: false,
    ping: undefined,
    tag: "Выживание",
  },
  {
    id: "13",
    name: "AncientEarth PE",
    host: "ancient.mcpehub.net",
    port: 19132,
    description: "Выживание с историческим уклоном: эпохи развития, деревянный → каменный → железный век",
    version: "1.20",
    online: true,
    players: 303,
    maxPlayers: 600,
    favorite: false,
    ping: 55,
    tag: "RPG",
  },
  {
    id: "14",
    name: "SkyRoots SMP",
    host: "skyroots.mcpehub.net",
    port: 19132,
    description: "SkyBlock выживание с нуля на парящем острове. Квесты, торговля между игроками, острова-соседи",
    version: "1.19+",
    online: true,
    players: 867,
    maxPlayers: 1500,
    favorite: false,
    ping: 38,
    tag: "SkyBlock",
  },
  {
    id: "15",
    name: "EmberCore SMP",
    host: "ember.mcpehub.net",
    port: 19132,
    description: "PvE выживание с боссами и данжами. Рейды каждую пятницу, уникальные лутбоксы за победы",
    version: "1.21",
    online: true,
    players: 455,
    maxPlayers: 900,
    favorite: false,
    ping: 61,
    tag: "PvE",
  },
];